name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        haxe: [4.2.5, latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: kLabz/setup-haxe@bb4d566a79354f25a29002f76a36bc54ead97e30
        with:
          haxe-version: ${{ matrix.haxe }}
          haxe-nightly: ${{ matrix.haxe == 'latest' }}

      - run: haxe -version
      - run: haxelib install --always install.hxml

      - name: Compile tools
        run: haxe build.hxml

      - name: Repro xredefined
        # This repro only reproduces on nightlies
        if: ${{ matrix.haxe == 'latest' }}
        run: |
          cd projects/xredefined
          node ../../bin/replay.js --path recording --file repro.log
          node ../../bin/replay.js --path recording --file repro-1.log
          node ../../bin/replay.js --path recording --file repro-2.log
